name: Validation check
on:
  push:
    branches: ['master']
    paths: ['scraper/**']
  pull_request:
    branches: ['master']
    paths: ['scraper/**']
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - name: Cargo check
        timeout-minutes: 2
        run: cargo check --locked
      - name: Confirm code format
        run: cargo fmt -- --check
      - name: Unit test and generate code coverage
        run: cargo +nightly tarpaulin --verbose --timeout 120
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: muhrifqii/opdb-rust
